name: brew
on: push
jobs:
  brew:
    if: github.ref == 'refs/heads/main'
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          scripts/brew-env.sh
          brew update --force --quiet
          brew upgrade
          brew config
          brew ls
          brew bundle
